package backpropagation_mlp;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

public final class FrmCamara extends javax.swing.JFrame {

    
    int largoCamara = 640;
    int anchoCamara = 480;
    BufferedImage[] ruta = new BufferedImage[60];
    int contador = 0;
    Dimension dimension = new Dimension(largoCamara,anchoCamara);
    Dimension dimension1 = WebcamResolution.VGA.getSize();
    Webcam webcam = Webcam.getDefault();
    WebcamPanel webcamPanel = new WebcamPanel(webcam,dimension,false);
    
    public FrmCamara() {
        initComponents();
        setLocationRelativeTo(null);
        webcam.setViewSize(dimension);
        webcamPanel.setFillArea(true);
        pnlCamara.setLayout(new FlowLayout());
        pnlCamara.add(webcamPanel);
        lblNombreCamara.setText(webcam.toString());
        apagarBotones();
    }
    
    public void apagarBotones(){
        btnOFF.setEnabled(false);
        btnCamara.setEnabled(false);
        btnGuardar.setEnabled(false);
    }
    
    public void prenderBotones(){
        btnOFF.setEnabled(true);
        btnCamara.setEnabled(true);
    }
    
    public void textoBotonesCargaCamara(){
        btnOFF.setText("Iniciando camara...");
        btnCamara.setText("Iniciando camara...");
        btnGuardar.setText("Iniciando camara...");
        btnON.setText("Iniciando camara...");
    }
    
    public void textoBotonesCargoGrabacion(){
        btnOFF.setText("Grabando...");
        btnCamara.setText("Grabando...");
        btnGuardar.setText("DESCARGAR");
        btnON.setText("Grabando...");
    }
    
    public void textoBotonesCargoCamara(){
        btnOFF.setText("APAGAR");
        btnCamara.setText("INICIAR VIDEO");
        btnGuardar.setText("DESCARGAR");
        btnON.setText("INICIAR");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOFF = new javax.swing.JButton();
        btnON = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCamara = new javax.swing.JButton();
        pnlCamara = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreCamara = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAMARA ");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        btnOFF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/off.png"))); // NOI18N
        btnOFF.setText("APAGAR");
        btnOFF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOFF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOFF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOFFActionPerformed(evt);
            }
        });

        btnON.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/on.png"))); // NOI18N
        btnON.setText("INICIAR");
        btnON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnON.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnON, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(btnOFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnON, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOFF)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/download.png"))); // NOI18N
        btnGuardar.setText("GUARDAR FOTOS");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCamara.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCamara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/photo.png"))); // NOI18N
        btnCamara.setText("INICIAR GRABACION");
        btnCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamaraActionPerformed(evt);
            }
        });

        pnlCamara.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlCamaraLayout = new javax.swing.GroupLayout(pnlCamara);
        pnlCamara.setLayout(pnlCamaraLayout);
        pnlCamaraLayout.setHorizontalGroup(
            pnlCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        pnlCamaraLayout.setVerticalGroup(
            pnlCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Camara en uso");

        lblNombreCamara.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombreCamara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCamara.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCamara)
                        .addGap(28, 28, 28)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNombreCamara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(28, 28, 28)
                        .addComponent(pnlCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreCamara)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnCamara))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnONActionPerformed
        textoBotonesCargaCamara();
        Thread hilo = new Thread(){
            @Override
            public void run(){
               webcamPanel.start();
               prenderBotones();
               textoBotonesCargoCamara();
            }
        };
        hilo.setDaemon(true);
        hilo.start();
        btnON.setEnabled(false);
    }//GEN-LAST:event_btnONActionPerformed

    private void btnOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOFFActionPerformed
        webcamPanel.stop();
        apagarBotones();
        btnON.setEnabled(true);
    }//GEN-LAST:event_btnOFFActionPerformed

    private void btnCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamaraActionPerformed
       textoBotonesCargoGrabacion();
       for(int i=0;i<=59;i++){
            ruta[i] = webcam.getImage();
        }
        //textoBotonesCargoGrabacion();
        btnCamara.setEnabled(false);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnCamaraActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        for(int i=0;i<=59;i++){
            File salidaImagen = new File("C:\\Users\\CAMILO\\Documents\\UNIVERSIDAD\\INTELIGENCIA ARTIFICIAL\\Backpropagation_MLP\\images\\Foto"+contador+".png");
            try{
                ImageIO.write(ruta[i], "png", salidaImagen);             
            }catch(Exception e){
                System.out.println("Error: "+ e);
            }
            btnGuardar.setEnabled(false);
            btnCamara.setEnabled(true);
            textoBotonesCargoCamara();
            contador++;
        }
        /*File salidaImagen = new File("C:\\Users\\CAMILO\\Documents\\UNIVERSIDAD\\INTELIGENCIA ARTIFICIAL\\Foto\\Foto"+contador+".jpg");
        try{
                ImageIO.write(ruta, "jpg", salidaImagen);             
        }catch(Exception e){
            System.out.println("Error: "+ e);
        }
        btnGuardar.setEnabled(false);
        btnCamara.setText("CAPTURAR FOTO");
        contador++;*/
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCamara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamara;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOFF;
    private javax.swing.JButton btnON;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombreCamara;
    private javax.swing.JPanel pnlCamara;
    // End of variables declaration//GEN-END:variables
}
